# Generated by Django 3.1.5 on 2021-01-10 12:46

from django.db import migrations, models
import django.db.models.deletion

# здесь мы видим, что миграция моделей произведена

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200, null=True, verbose_name='Текст ответа')),
                ('votes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['quest_id'],
            },
        ),
        migrations.CreateModel(
            name='PollsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_poll', models.CharField(max_length=200, verbose_name='Название анкеты')),
                ('description_text', models.TextField(blank=True, null=True, verbose_name='Описание опроса')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'ordering': ['date_start'],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('type_quest', models.CharField(choices=[('S', 'Один ответ'), ('M', 'Несколько ответов'), ('T', 'Ответ текстом')], default='S', max_length=1, verbose_name='Варианты ответов')),
                ('polls_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls_app.pollsdb', verbose_name='Название опроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['polls_id'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=1)),
                ('user_ip', models.CharField(default='127.0.0.1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200, null=True, verbose_name='Текст ответа пользователя, если выбран текстовый ответ')),
                ('id_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='polls_app.answers')),
                ('id_polls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_polls', to='polls_app.pollsdb')),
                ('id_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_questions', to='polls_app.questions')),
                ('id_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='polls_app.users')),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='quest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls_app.questions'),
        ),
    ]
